version: 2

project_name: frostnews2mqtt

before:
  hooks:
  - go mod tidy

env:
  - PACKAGE_PATH=github.com/berfenger/frostnews2mqtt/cmd

builds:
- id: fro-build
  binary: frostnews2mqtt
  main: ./cmd/api
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  - arm
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X {{.Env.PACKAGE_PATH}}={{.Version}}
release:
  prerelease: auto

universal_binaries:
- replace: true

archives:
  - name_template: >
      {{- .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

kos:
  - id: ghcr-publish
    build: fro-build
    repository: ghcr.io/berfenger/frostnews2mqtt
    tags:
      - "{{.Tag}}"
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - all
  - id: hub-publish
    build: fro-build
    repository: acasal/frostnews2mqtt
    tags:
      - "{{.Tag}}"
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - all
