version: 2

project_name: frostnews2mqtt

before:
  hooks:
  - go mod tidy

env:
  - PACKAGE_PATH=github.com/berfenger/frostnews2mqtt/cmd

builds:
- id: api-build
  binary: frostnews2mqtt
  main: ./cmd/api
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
    - arm
  goarm:
    - 7
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X {{.Env.PACKAGE_PATH}}={{.Version}}
release:
  prerelease: auto

universal_binaries:
- replace: true

archives:
  - name_template: >
      {{- .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

dockers:
  - ids:
      - api-build
    image_templates:
      - &amd_image "acasal/frostnews2mqtt:{{ .Version }}-amd64"
      - &g_amd_image "ghcr.io/berfenger/frostnews2mqtt:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/berfenger/frostnews2mqtt"
      - "--label=org.opencontainers.image.url=https://github.com/berfenger/frostnews2mqtt"
      - "--label=org.opencontainers.image.licenses=Apache 2.0"
      - "--platform=linux/amd64"
    goarch: amd64
  - ids:
      - api-build
    image_templates:
      - &arm64_image "acasal/frostnews2mqtt:{{ .Version }}-arm64"
      - &g_arm64_image "ghcr.io/berfenger/frostnews2mqtt:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/berfenger/frostnews2mqtt"
      - "--label=org.opencontainers.image.url=https://github.com/berfenger/frostnews2mqtt"
      - "--label=org.opencontainers.image.licenses=Apache 2.0"
      - "--platform=linux/arm64"
    goarch: arm64
  - ids:
      - api-build
    image_templates:
      - &armv7_image "acasal/frostnews2mqtt:{{ .Version }}-armv7"
      - &g_armv7_image "ghcr.io/berfenger/frostnews2mqtt:{{ .Version }}-armv7"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/berfenger/frostnews2mqtt"
      - "--label=org.opencontainers.image.url=https://github.com/berfenger/frostnews2mqtt"
      - "--label=org.opencontainers.image.licenses=Apache 2.0"
      - "--platform=linux/arm/v7"
    goarch: arm
    goarm: 7

docker_manifests:
  - name_template: "acasal/frostnews2mqtt:latest"
    image_templates:
      - *amd_image
      - *arm64_image
      - *armv7_image
    create_flags:
      - --insecure
    push_flags:
      - --insecure
  - name_template: "acasal/frostnews2mqtt:{{ .Version }}"
    image_templates:
      - *amd_image
      - *arm64_image
      - *armv7_image
    create_flags:
      - --insecure
    push_flags:
      - --insecure
  - name_template: "ghcr.io/berfenger/frostnews2mqtt:latest"
    image_templates:
      - *g_amd_image
      - *g_arm64_image
      - *g_armv7_image
    create_flags:
      - --insecure
    push_flags:
      - --insecure
  - name_template: "ghcr.io/berfenger/frostnews2mqtt:{{ .Version }}"
    image_templates:
      - *g_amd_image
      - *g_arm64_image
      - *g_armv7_image
    create_flags:
      - --insecure
    push_flags:
      - --insecure

