mqtt:
  host: localhost
  port: 1883
  username:
  password:
  base_topic: frostnews11
  ha_discovery_enable: true
  #ha_discovery_topic: homeassistant

inverter_modbus_tcp:
  host: 192.168.1.4
  port: 502
  meter_id: 200
  inverter_id: 0
  ignore_fronius: false
  read_delay_after_change_millis: 2000

monitor:
  poll_interval_millis: 5000
  track_house_power: true

grid:
  max_import_power: 4000

battery_control:
  control_interval_millis: 4000
  start_power_threshold: 500
  max_rate_power_increase: 800
  safety_margin_power: 200