services:
  frostnews2mqtt:
    image: acasal/frostnews2mqtt:latest
    container_name: frostnews2mqtt
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yml
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      CONFIG_FILE: /config.yml
